apiVersion: v1
kind: Service
metadata:
  name: kiwix-loadbalancer
  namespace: kiwix-ns
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: kiwix-web
    nodePort: 30071
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-kiwix-ns-kiwix
  sessionAffinity: None
  type: LoadBalancer
