apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwix-pvc
  namespace: kiwix-ns
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  volumeName: {{ .Values.storage.volume_name }}
  resources:
    requests:
      storage: {{ .Values.storage.storage_size }}