apiVersion: v1
kind: Service
metadata:
  name: kiwix
  namespace: kiwix-ns
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: kiwix-web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-kiwix-ns-kiwix
  sessionAffinity: None
  type: ClusterIP
