apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: kiwix-web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload: {{ .Release.Name }}-pod
  sessionAffinity: None
  type: ClusterIP
