apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  volumeName: {{ .Values.storage.volume_name }}
  resources:
    requests:
      storage: {{ .Values.storage.storage_size }}