apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-loadbalancer
  namespace: {{ .Values.namespace }}
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: {{ .Release.Name }}-web
    nodePort: 30071
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-kiwix-ns-kiwix
  sessionAffinity: None
  type: LoadBalancer
